# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zuvito
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: star-wars-with-berries-v1
# "service" is the name of this project. This will also be added to your AWS resource names.
service: starwars-planets-with-berries

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

# plugins:
#   - serverless-plugin-typescript

# custom:
#   serverlessPluginTypescript:
#     tsConfigFileLocation: "./tsconfig.build.json"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
