# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zuvito
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: star-wars-with-berries-v1
# "service" is the name of this project. This will also be added to your AWS resource names.
service: starwars-planets-with-berries

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.awsRegion}

  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

custom:
  cacheDynamoDBTable: "StarWarsCacheTable"
  historicalDynamoDBTable: "StarWarsHistoricalResponseTable"
  awsRegion: us-east-1

functions:
  hello:
    handler: handler.getPlanets
    events:
      - httpApi:
          path: /planet/{id}
          method: get
    environment:
      CACHE_TABLE_NAME: ${self:custom.cacheDynamoDBTable}
      HISTORICAL_TABLE_NAME: ${self:custom.historicalDynamoDBTable}
      REGION: ${self:custom.awsRegion}

    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:*:*:table/${self:custom.cacheDynamoDBTable}
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - arn:aws:dynamodb:*:*:table/${self:custom.historicalDynamoDBTable}

resources:
  Resources:
    StarWarsCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.cacheDynamoDBTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - KeyType: HASH
            AttributeName: id
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    StarWarsHistoricalResponseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.historicalDynamoDBTable}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
